### ISSUE TITLE
Example for Particle Test and Playback Not Functioning

### ISSUE THREAD

**Issue by kmccaffr** [ScruffR/Adafruit_VS1053_Library#1]
I just wanted to confirm that the SdFat.h is referencing the most recent library from https://github.com/greiman/SdFat-Particle with the additional src libraries, correct? As the examples compile but don't actually initialize the VS1053? I'm trying to switch over to your more recent library code to address one of the issues i'm having with a more basic version of this library.

* I know it's not a hardware issue because I have been using the more basic particle library available (https://github.com/McTristan/Adafruit_VS1053_Library_Photon) and everything correctly functions except when calling **startPlayingFile** as opposed to **playFullFile** in main code. I just receive a **heap stack error** after buffer is finished and my photon locks up.

Anyways, if you could confirm all the libraries used that would be helpful.

Photon OS: 1.2.1

**Comment by ScruffR** [comment]
Only the example explicitly called `ParticleTest` was created for the Particle platform. 
The other examples are still in their original state as they came from Adafruit.

The problem with newer device OS versions is that Particle introduced a new "security" check which causes an SOS+14 but that seems to be a bit overzealous

See the comment thread in this 
https://github.com/particle-iot/device-os/issues/1835

**Comment by kmccaffr** [comment]
I will give those a look to see if that's what was causing my issue (I swear that I wasn't receiving this heap error a few months ago). Hopefully uploading a different OS is straight forward, thank you for responding!

**Comment by kmccaffr** [comment]
Hi @ScruffR, reverting back to OS version 1.1.1 resolved the entire issue. That new security feature was locking up the VS1053 code. Thank you again!
